# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20190112_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=None),
        ),
    ]
