# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-12 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190112_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='List',
        ),
    ]
