# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-13 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_remove_list_deadline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Task',
        ),
    ]
